# Generated by Django 3.0.8 on 2020-08-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Balance Sheet')),
                ('date_2019', models.CharField(max_length=60, verbose_name=0.00019811788013868252)),
                ('date_2018', models.CharField(max_length=60, verbose_name=0.00019821605550049556)),
                ('date_2017', models.CharField(max_length=60, verbose_name=0.0001983143282102132)),
                ('date_2016', models.CharField(max_length=60, verbose_name=0.0001984126984126984)),
            ],
        ),
    ]
