# Generated by Django 3.0.8 on 2020-08-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalist',
            name='date_2016',
            field=models.CharField(max_length=60, verbose_name='12/30/2016'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='date_2017',
            field=models.CharField(max_length=60, verbose_name='12/30/2017'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='date_2018',
            field=models.CharField(max_length=60, verbose_name='12/30/2018'),
        ),
        migrations.AlterField(
            model_name='datalist',
            name='date_2019',
            field=models.CharField(max_length=60, verbose_name='12/30/2019'),
        ),
    ]
