# Generated by Django 3.0.8 on 2020-08-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200802_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datalist',
            options={'verbose_name': 'Данные компании', 'verbose_name_plural': 'Данные компании'},
        ),
    ]
